[build]
builder = "nixpacks"

[deploy]
# jangan migrate di sini
start = "php artisan serve --host 0.0.0.0 --port $PORT"

# setelah app berhasil start, migrate 1x
[deploy.hooks]
postStart = "php artisan migrate --force"
