[build]
builder = "nixpacks"

[deploy]
start = "php artisan serve --host 0.0.0.0 --port ${PORT}"

[deploy.hooks]
# build assets setelah install dependencies
postInstall = "npm install && npm run build"
postStart = "php artisan migrate --force"
